# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:

    - step:
        name: 'Git sync start'
        script:
          - echo "Sync has started..."
    - step:
        name: 'Git sync job'
        #trigger: 'manual'
        script:
          - echo "Syncing in progress..."
          - git clone --mirror https://github.com/iakovos3/spring-boot-up-embedded-keycloak.git
          - cd spring-boot-up-embedded-keycloak.git
          - git remote set-url --push origin ${BITBUCKET_GIT_SSH_ORIGIN}
          - git fetch -p origin
          - git push --mirror
    - step:
        name: 'Git sync finish'
        script:
          - echo "Sync has finished!"
